# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sweHW7',
                'doc_host': 'https://noahschulman14.github.io',
                'git_url': 'https://github.com/noahschulman14/sweHW7',
                'lib_path': 'sweHW7'},
  'syms': {'sweHW7.core': {'sweHW7.core.foo': ('core.html#foo', 'sweHW7/core.py')}}}
